* Python does not have built-in support for arrays.
* So everytime we need to use arrays, we will have to specify it.
* However, Python provides built-in support for lists
* If you are using lists, you will not have to specify it.

In [1]:
from numpy import array

num_array = array([1,2,3,4])

num_list = [1,2,3,4]

print(num_array)
print(num_list)

[1 2 3 4]
[1, 2, 3, 4]


* You can do math operations on a Python array containing numbers
* you may not do the same for lists

In [2]:
num_array = array([1,2,3,4])
print(num_array / 4)

[0.25 0.5  0.75 1.  ]


In [3]:
num_list = [1,2,3,4]
print(num_list/4)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [12]:
num_array = array([1,2,3,4])
print(type(num_array[0]))

num_array = array([1,2,3,4,'4'])
print(num_array)


<class 'numpy.int64'>
['1' '2' '3' '4' '4']


In [15]:
num_list = [1,2,3,4,'4']
print(num_list)
print(type(num_list[4]))

[1, 2, 3, 4, '4']
<class 'str'>


* You can do multiple Arithmetic operations on an array

In [16]:
num_array = array([1,2,3,4])
num_array = num_array ** 2
print(num_array)

[ 1  4  9 16]


In [17]:
num_array = array([1,2,3,4])
num_array = (num_array + 2) / 4
print(num_array)

[0.75 1.   1.25 1.5 ]


In [19]:
num_array = array([1,2,3,4])
num_array = num_array + num_array
print(num_array)
num_list = [1,2,3,4]
num_list = num_list + num_list
print(num_list)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [20]:
list_1 = [1, 12, "Ross", 44]
list_2 = [2, 34, "Rachel", 55]

list_1.append("Chandler") # add an item to the end of the list
list_2.append("Monica")

print(list_1)
print(list_2)

[1, 12, 'Ross', 44, 'Chandler']
[2, 34, 'Rachel', 55, 'Monica']


In [21]:
list_1_2 = list_1 + list_2
print(list_1_2)

list_1.extend(list_2) # concatantes two lists; here extends list_1 to include the items in list_2

print(list_1)

[1, 12, 'Ross', 44, 'Chandler', 2, 34, 'Rachel', 55, 'Monica']
[1, 12, 'Ross', 44, 'Chandler', 2, 34, 'Rachel', 55, 'Monica']


In [23]:
list_1.insert(2, "Joey") # inserts item to the given index
print(list_1)

[1, 12, 'Joey', 'Joey', 'Ross', 44]


In [24]:
list_1.remove("Joey") # removes the item that mathches the given value
print(list_1)

[1, 12, 'Joey', 'Ross', 44]


In [26]:
list_1.pop(0) # remvoes item at teh given index
print(list_1)

['Joey', 'Ross', 44]


In [27]:
list_1.index("Ross")

1

In [29]:
list_1 = [1, 12, 'Joey', 'Joey', 'Ross', 44]
list_1.count("Joey")

2

In [32]:
num_list = [1,4,5,-9]
num_list.sort()
print(num_list)

[-9, 1, 4, 5]


In [33]:
num_list = [1,4,5,-9]
num_list.sort(reverse=True)
print(num_list)


[5, 4, 1, -9]


In [34]:
len(num_list) # length of the list_1; That is, it returns how many items are there in the list.

4

In [35]:
print(max(num_list))

5


In [36]:
print(min(num_list))

-9


In [37]:
print(list(range(1,10))) # includes the start number, excludes the end number, presents all the numbers in between

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [38]:
print(list(range(1,10,3))) # includes start number, excludes end number, increments or decrements by the third number

[1, 4, 7]


In [39]:
print(list(range(100,10,-3))) # this time decrement by 3

[100, 97, 94, 91, 88, 85, 82, 79, 76, 73, 70, 67, 64, 61, 58, 55, 52, 49, 46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13]
