In [3]:
from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

In [5]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])
print(cosine_similarity([X, Y]))

[[1.         0.96886393]
 [0.96886393 1.        ]]


In [7]:
# Let's test the fact that the similarity is not dependent on their magnitude

X = X/ max(X)
X

array([0.25, 0.5 , 0.75, 1.  ])

In [9]:
Y = Y/max(Y)
Y

array([0.625, 0.75 , 0.875, 1.   ])

In [10]:
print(cosine_similarity([X, Y]))

[[1.         0.96886393]
 [0.96886393 1.        ]]


In [ ]:
X = np.array([1,2,3,4])
Y = 3 * Y
Y