1. **[30 points]** In the cell beow, write necessary code to create a NumPy array of random integers. The max value of the integers should be 50. The shape of the array should be (3,3).

In [11]:
import numpy as np
rand_arr = np.random.randint(50, size=(3,3))
print(rand_arr)

[[24 43 30]
 [40  7 10]
 [24 40 15]]


2. **[30 points]** The following code stores the iris dataset in the dataframe df. Create a new dataframe only using the columns petal_length and petal_width. Name the new datafram as df_new.

In [13]:
import seaborn as sns
# also, if seaborn is not installed, Google how to install, or ask me

df = sns.load_dataset('iris')
print(df.columns)

df_new = df[['petal_width', 'petal_length']]
df_new

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


petal_width  petal_length
0            0.2           1.4
1            0.2           1.4
2            0.2           1.3
3            0.2           1.5
4            0.2           1.4
..           ...           ...
145          2.3           5.2
146          1.9           5.0
147          2.0           5.2
148          2.3           5.4
149          1.8           5.1

[150 rows x 2 columns]

3. **[30 points]** Find column wise mean of df_new and print those values.

In [15]:
df_mean = df_new.mean(axis=0)
print(df_mean)

petal_width     1.199333
petal_length    3.758000
dtype: float64


4. **[BONUS: 30 points]** Extract the rows from 20 to 29 from df_new in a NumPy array. Find the max value in each row using NumPy syntaxes. 


In [16]:
import numpy as np
df_np = df_new.values
print(type(df_new))
print(type(df_np))
col_1_max = np.max(df_np[:,0])
col_2_max = np.max(df_np[:,1])
print(col_1_max)
print(col_2_max)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
2.5
6.9
